# Generated by Django 4.1.3 on 2022-11-08 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_name_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='name_id',
        ),
    ]
