# Generated by Django 4.1.3 on 2022-11-08 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_customuser_name_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
