# Generated by Django 4.1.3 on 2022-11-08 18:38

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Type_of_transcation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_transaction_date', models.DateField(default=datetime.date(2022, 11, 8))),
                ('item_name', models.CharField(max_length=80)),
                ('item_price', models.FloatField()),
                ('item_category_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='kursach.categories')),
                ('item_type_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='kursach.type_of_transcation')),
                ('item_user_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Check_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_name', models.CharField(max_length=80)),
                ('check_count', models.FloatField()),
                ('check_price', models.FloatField()),
                ('check_transaction_date', models.DateField(default=datetime.date(2022, 11, 8))),
                ('check_category_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='kursach.categories')),
                ('check_user_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Данные',
            },
        ),
    ]
