# Generated by Django 4.1.2 on 2022-10-27 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kursach', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='CheckData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemName', models.CharField(max_length=80)),
                ('itemCount', models.FloatField()),
                ('itemPrice', models.FloatField()),
            ],
            options={
                'verbose_name': 'Данные',
            },
        ),
        migrations.CreateModel(
            name='TypeOfTranscation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeName', models.CharField(max_length=80)),
            ],
        ),
        migrations.AlterField(
            model_name='checkmodel',
            name='checkImg',
            field=models.ImageField(upload_to='images/%Y/%m/%d/'),
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactionDate', models.DateField()),
                ('checkId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kursach.checkdata')),
                ('itemCategoryId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kursach.categories')),
                ('typeId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kursach.typeoftranscation')),
            ],
        ),
    ]
