# Generated by Django 4.1.3 on 2022-11-08 20:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kursach', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='item_transaction_date',
            field=models.DateField(blank=True, default=datetime.date(2022, 11, 8)),
        ),
    ]
