# Generated by Django 4.1.2 on 2022-10-28 08:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kursach', '0002_categories_checkdata_typeoftranscation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkdata',
            name='itemCategoryId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='kursach.categories'),
        ),
        migrations.AddField(
            model_name='checkdata',
            name='itemTransactionDate',
            field=models.DateField(default=datetime.date(2022, 10, 28)),
        ),
        migrations.AddField(
            model_name='checkdata',
            name='itemTypeId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='kursach.typeoftranscation'),
        ),
        migrations.AddField(
            model_name='checkdata',
            name='itemUniq',
            field=models.CharField(default=1, max_length=80),
        ),
        migrations.DeleteModel(
            name='Transactions',
        ),
    ]
