# Generated by Django 4.1.3 on 2022-11-08 20:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kursach', '0002_alter_transactions_item_transaction_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='item_transaction_date',
            field=models.DateField(blank=True, default=datetime.date(2022, 11, 8), null=True),
        ),
    ]
