# Generated by Django 4.1.3 on 2022-11-08 21:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kursach', '0003_alter_transactions_item_transaction_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check_data',
            name='check_transaction_date',
            field=models.DateField(default=datetime.date(2022, 11, 9)),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='item_category_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='kursach.categories', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='item_name',
            field=models.CharField(max_length=80, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='item_price',
            field=models.FloatField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='item_transaction_date',
            field=models.DateField(blank=True, default=datetime.date(2022, 11, 9), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='item_type_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='kursach.type_of_transcation', verbose_name='Тип'),
        ),
    ]
