# Generated by Django 4.1.3 on 2022-11-08 21:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kursach', '0004_alter_check_data_check_transaction_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='item_transaction_date',
            field=models.DateField(default=datetime.date(2022, 11, 9), verbose_name='Дата'),
        ),
    ]
