# Generated by Django 4.1.3 on 2022-11-09 20:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kursach', '0005_alter_transactions_item_transaction_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='category_user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
