# Generated by Django 4.1.3 on 2022-11-11 11:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kursach', '0006_categories_category_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(max_length=80)),
                ('news_date', models.DateField()),
                ('news_text', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='categories',
            name='category_name',
            field=models.CharField(max_length=80, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='check_data',
            name='check_transaction_date',
            field=models.DateField(default=datetime.date(2022, 11, 11)),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='item_transaction_date',
            field=models.DateField(verbose_name='Дата'),
        ),
    ]
