# Generated by Django 4.1.3 on 2022-11-13 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kursach', '0008_alter_check_data_check_transaction_date_bill'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bill',
            options={'verbose_name': 'Счёт', 'verbose_name_plural': 'Счета'},
        ),
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='check_data',
            options={'verbose_name': 'Чек', 'verbose_name_plural': 'Чеки'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterModelOptions(
            name='transactions',
            options={'verbose_name': 'Транзакция', 'verbose_name_plural': 'Транзакции'},
        ),
        migrations.AlterModelOptions(
            name='type_of_transcation',
            options={'verbose_name': 'Тип транзакции', 'verbose_name_plural': 'Типы транзакций'},
        ),
        migrations.RenameField(
            model_name='check_data',
            old_name='check_transaction_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='transactions',
            old_name='item_transaction_date',
            new_name='date',
        ),
    ]
